name: Experimental Release
on:
  push:
    tags: [ "*-experimental" ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "RELEASE_VERSION=$(./scripts/version-from-git-tag.sh)-experimental" >> $GITHUB_ENV
      - run: echo "Publishing version $RELEASE_VERSION"
