name: Nightly Release
on:
  push:
    tags: [ "*-nightly" ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "RELEASE_VERSION=$(./scripts/version-from-git-tag.sh)-nightly" >> $GITHUB_ENV
      - run: echo "Publishing version $RELEASE_VERSION"
