name: Stable Release
on:
  workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "RELEASE_VERSION=$(./scripts/version-from-git-tag.sh)" >> $GITHUB_ENV
      - run: echo "Publishing version $RELEASE_VERSION"
      - run: |
          git remote set-url origin https://${GITHUB_TOKEN}@github.com/mkondratek/jetbrains.git
      - run: git tag -a "RELEASE_VERSION" -m "RELEASE_VERSION" && git push origin "$RELEASE_VERSION"
